name: PvN_Manager
version: 0.1-SNAPSHOT
main: usa.cactuspuppy.pvn_bot.Main
description: Manages Pirates vs. Ninjas event, including Discord integration
author: CactusPuppy
website: github.com/CactusPuppy

permissions:
  pvn.admin:
    description: Allows holder to manage the bot.

commands:
  pvn:
    description: Wrapper command to access the bot.
    permission: pvn.admin
  group:
    description: Groups player with the specified player if they are close enough.
  t:
    description: Sends message to teammates
